syntax keyword Tag syntax keyword Tag !_TAG_FILE_FORMAT
syntax keyword Tag syntax keyword Tag !_TAG_FILE_SORTED
syntax keyword Tag syntax keyword Tag !_TAG_PROGRAM_AUTHOR
syntax keyword Tag syntax keyword Tag !_TAG_PROGRAM_NAME
syntax keyword Tag syntax keyword Tag !_TAG_PROGRAM_URL
syntax keyword Tag syntax keyword Tag !_TAG_PROGRAM_VERSION
syntax keyword Tag syntax keyword Tag t
syntax keyword Tag syntax keyword Tag f
syntax keyword Tag syntax keyword Tag x
syntax keyword Tag syntax keyword Tag v
syntax keyword Tag syntax keyword Tag a
syntax keyword Tag syntax keyword Tag main
syntax keyword Tag syntax keyword Tag n31
syntax keyword Tag syntax keyword Tag calculator
syntax keyword Tag syntax keyword Tag Application
syntax keyword Tag syntax keyword Tag __init__
syntax keyword Tag syntax keyword Tag replaceText
syntax keyword Tag syntax keyword Tag appendToDisplay
syntax keyword Tag syntax keyword Tag calculateExpression
syntax keyword Tag syntax keyword Tag clearText
syntax keyword Tag syntax keyword Tag createWidgets
syntax keyword Tag syntax keyword Tag app
syntax keyword Tag syntax keyword Tag absMax
syntax keyword Tag syntax keyword Tag main
syntax keyword Tag syntax keyword Tag absMin
syntax keyword Tag syntax keyword Tag main
syntax keyword Tag syntax keyword Tag absVal
syntax keyword Tag syntax keyword Tag main
syntax keyword Tag syntax keyword Tag find_hcf
syntax keyword Tag syntax keyword Tag main
syntax keyword Tag syntax keyword Tag find_lcm
syntax keyword Tag syntax keyword Tag main
syntax keyword Tag syntax keyword Tag find_max
syntax keyword Tag syntax keyword Tag main
syntax keyword Tag syntax keyword Tag main
syntax keyword Tag syntax keyword Tag findMin
