* var vah
      yah             - yank heading
      dah             - delete heading
      yar             - yank subtree
      dar             - delete subtree
      p               - paste subtree

* PROMOTE
      << or <ah       - promote heading
      >> or >ah       - demote heading
      <ar             - promote subtree
      >ar             - demote subtree
      -list 03022019
      -list2
      -list3

* TODO Lists:~									     :CULT:
    <localleader>d  - select keyword
    <S-Left>        - previous keyword
    <S-Right>       - next keyword
    <C-S-Left>      - previous keyword set
    <C-S-Right>     - next keyword set

  Plain List:~
    <localleader>cl or <CR>     - insert plainlist item below
    <localleader>cL or <C-S-CR> - insert plainlist item above

* TODO Checkboxes[80%][4/5]:~							     :CULT:
    - [X] <localleader>cc             - toggle status
    - [X] <localleader>cn or <CR>     - insert checkbox below
    - [X] <localleader>cN or <C-S-CR> - insert checkbox above
    - [ ] dxxxd <2020-02-03 Mon>
    - [X] <2020-02-03 Mon>

  TAGS and properties:~
    <localleader>st     - set tags

* Dates:~
    <localleader>sa     - insert date
    <localleader>si     - insert inactive date
    <localleader>pa     - insert date by using calendar selection
    <localleader>pi     - insert inactive date by using calendar selection
    <localleader>pi     - insert inactive date by using calendar selection

* Agenda:~
    <localleader>caa    - agenda for the week
    <localleader>cat    - agenda of all TODOs
    <localleader>caA    - agenda for the week for current buffer
    <localleader>caT    - agenda of all TODOs for current buffer

    Not yet implemented in vim-orgmode~
    <localleader>caL    - timeline of current buffer

    <localleader>d  - select keyword
    <S-Left>        - previous keyword
    <S-Right>       - next keyword
    <C-S-Left>      - previous keyword set
    <C-S-Right>     - next keyword set

* Structure editing~
  <S-CR>                Insert new heading with same level as current. If the
                        cursor is in a plain list item, a new item is created
                        (see section [[#Plain-lists][Plain lists]]). When this
                        command is used in the middle of a line, the line is
                        split and the rest of the line becomes the new
                        headline.

  Not yet implemented in vim-orgmode~
  M-S-<CR>              Insert new TODO entry with same level as current
                        heading.

* Export:~
    <localleader>ep     - export as PDF
    <localleader>eb     - export as Beamer PDF
    <localleader>eh     - export as HTML
    <localleader>el     - export as LaTeX
    <localleader>el     - export as LaTeX

* Note:
  - /italic/ is rendered as reverse in most terms (works fine in gVim, though)
  - +strike-through+ doesn't work on Vim / GVim
  - the non-standard `code' markup is also supported
  - =code= and ~verbatim~ are also supported as block-level markup, see below.
  - =code= and ~verbatim~ are also supported as block-level markup, see below.

* Link
[[www.web.de][WEB]]
[[https://devhints.io/projectionist][io]]
[[https://devhints.io/projectionist][io]]
[[https://devhints.io/projectionist][io]]
[[https://devhints.io/projectionist][io]]
** Hyperlinks:~
- Li
- li
    gl              - goto link
    gyl             - yank link
    gil             - insert new link
    gn              - next link
    go              - previous link

*** Link
      [[link][description]]       or alternatively           [[link]]
      'Insert/edit Link' command by pressing 'gil'.

      gil                   Insert a link. This prompts for a link to be inserted
                              into the buffer. You can just type a link, or use
                              history keys <Up> and <Down> to access stored links.
                              You will be prompted for the description part of the
                              link. File name completion is enabled to link to a
                              local file. In addition vim-orgmode provides the
                              command :OrgHyperlinkInsert to insert a link from
                              command line.


* TODO Organize party [1/3]
      - [-] call people [1/2]
            - [X] Peter
            - [ ] Sarah
      - [X] order food
      - [ ] think about what music to play
      - [ ] think about what music to play

* Lord of the Rings
     My favorite scenes are (in this order)
     1. The attack of the Rohirrim
     2. Eowyn's fight with the witch king
        + this was already my favorite scene in the book
        + I really like Miranda Otto.
     Important actors in this film are:
     - Elijah Wood :: He plays Frodo
     - Sean Austin :: He plays Sam, Frodo's friend.

* SyntaxHi
For quick, ad-hoc manipulation of the syntax withing a range of lines, the
following commands are provided:

:[range]SyntaxIgnore    Ignore the buffer's filetype syntax for the current
                        line / lines in [range]. (Top-level keywords will
                        still be highlighted.)
                        This can be a useful fix when some text fragments
                        confuse the syntax highlighting. (For example, when
                        buffer syntax set to an inlined here-document is
                        negatively affected by the foreign code surrounding
                        the here-document.)

:[range]SyntaxInclude {filetype}
                        Use the {filetype} syntax for the current line / lines
                        in [range].

                        Line numbers in [range] are fixed; i.e. they do not
                        adapt to inserted / deleted lines. But when in a

* Task for the day
** Morning Tasks [2/3]
   - [X] Exercise
   - [X] Eat breakfast
   - [ ] Read emails
** Server setup [0/3]
   - [ ] Buy account
   - [ ] Set up apache
   - [ ] Set up mysql
** Research [0/2]
   - [ ] How to use org mode
   - [ ] Wrtiing vim scripts
** Night tasks [0/2]
   - [ ] Read book
   - [ ] Write blog post
