[[snippets]]
  description = "1git-command"
  command = "git status"
  output = ""

[[snippets]]
  description = "exa-Tree"
  command = "exa --long --tree --level=3"
  output = ""

[[snippets]]
  description = "ls"
  command = "tig status"
  output = ""
